import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Sparkles, ArrowRight, Loader2, Target, Zap, ChevronRight, WifiOff } from 'lucide-react';
import { SubjectModule } from '../types';
import { getProgress } from '../lib/progressStore';
import { generateLearningPath, LearningPathRecommendation } from '../services/learningPathService';
import { useOffline } from '../hooks/useOffline';

interface AILearningPathProps {
  subject: SubjectModule;
  onTopicSelect: (topicId: string) => void;
}

export const AILearningPath: React.FC<AILearningPathProps> = ({ subject, onTopicSelect }) => {
  const [recommendation, setRecommendation] = useState<LearningPathRecommendation | null>(null);
  const [loading, setLoading] = useState(false);
  const isOffline = useOffline();

  const fetchLearningPath = async () => {
    if (isOffline) return;
    setLoading(true);
    const progress = getProgress();
    const result = await generateLearningPath(subject, progress);
    setRecommendation(result);
    setLoading(false);
  };

  useEffect(() => {
    fetchLearningPath();
  }, [subject, isOffline]);

  if (isOffline) {
    return (
      <div className="p-8 glass flex flex-col items-center justify-center text-center rounded-[2.5rem] border-dashed border-white/10 opacity-50">
        <WifiOff className="w-10 h-10 text-white/30 mb-4" />
        <h4 className="text-xl font-serif font-bold text-white mb-2">Wisey is Offline</h4>
        <p className="text-white/40 text-sm max-w-sm">Connect to the internet to receive personalized AI learning recommendations based on your performance.</p>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="p-12 glass flex flex-col items-center justify-center text-center rounded-[2.5rem] min-h-[400px]">
        <Loader2 className="w-10 h-10 text-orange-500 animate-spin mb-4" />
        <p className="text-white/50 text-sm font-medium">Wisey is analyzing your performance...</p>
        <p className="text-[10px] text-white/20 uppercase tracking-widest mt-2">Tailoring your learning path</p>
      </div>
    );
  }

  if (!recommendation) return null;

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-8"
    >
      <div className="glass-card p-8 md:p-12 rounded-[2.5rem] border-orange-500/10 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-orange-500/5 blur-[100px] rounded-full -mr-20 -mt-20" />
        
        <div className="relative z-10">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl bg-orange-500/20 flex items-center justify-center">
              <Sparkles className="w-5 h-5 text-orange-500" />
            </div>
            <div>
              <h3 className="text-2xl font-serif font-bold">AI Learning Path</h3>
              <p className="text-[10px] uppercase tracking-widest text-white/40">Generated by Wisey AI</p>
            </div>
          </div>

          <p className="text-white/70 leading-relaxed max-w-2xl mb-10 italic">
            "{recommendation.summary}"
          </p>

          <div className="grid md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <h4 className="text-xs font-bold uppercase tracking-widest text-orange-500/70 border-l-2 border-orange-500 pl-3">Priority Focus</h4>
              <div className="space-y-3">
                {recommendation.focusAreas.map((area, idx) => (
                  <motion.div 
                    key={idx}
                    whileHover={{ x: 4 }}
                    className="p-4 bg-white/5 border border-white/5 rounded-2xl flex items-start gap-4 cursor-pointer hover:border-orange-500/30 transition-all group"
                    onClick={() => onTopicSelect(area.topicId)}
                  >
                    <div className="w-8 h-8 rounded-lg bg-orange-500/10 flex items-center justify-center shrink-0">
                      <Target className="w-4 h-4 text-orange-500" />
                    </div>
                    <div>
                      <h5 className="font-bold text-sm mb-1 group-hover:text-orange-500 transition-colors">
                        {(() => {
                          const topicId = area.topicId;
                          let numbering = "";
                          for (const classTab of ['class11', 'class12'] as const) {
                            for (let cIdx = 0; cIdx < subject[classTab].length; cIdx++) {
                              const chapter = subject[classTab][cIdx];
                              const tIdx = chapter.topics.findIndex(t => t.id === topicId);
                              if (tIdx !== -1) {
                                numbering = `${cIdx + 1}.${tIdx + 1} `;
                                break;
                              }
                            }
                            if (numbering) break;
                          }
                          const topic = [...subject.class11, ...subject.class12]
                            .flatMap(c => c.topics)
                            .find(t => t.id === topicId);
                          return numbering + (topic?.title || "Topic Details");
                        })()}
                      </h5>
                      <p className="text-xs text-white/40 mb-2 truncate max-w-[200px]">{area.reason}</p>
                      <div className="flex items-center gap-1 text-[10px] font-bold text-orange-500 uppercase tracking-tighter">
                        {area.action} <ArrowRight className="w-3 h-3" />
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>

            <div className="space-y-4">
              <h4 className="text-xs font-bold uppercase tracking-widest text-blue-500/70 border-l-2 border-blue-500 pl-3">Smart Suggestions</h4>
              <div className="space-y-3">
                {recommendation.nextSteps.map((step, idx) => (
                  <div key={idx} className="p-4 bg-white/5 border border-white/5 rounded-2xl flex items-center gap-4">
                    <div className="w-8 h-8 rounded-lg bg-blue-500/10 flex items-center justify-center shrink-0">
                      <Zap className="w-4 h-4 text-blue-500" />
                    </div>
                    <p className="text-sm text-white/60">{step}</p>
                  </div>
                ))}
                
                <button 
                  onClick={fetchLearningPath}
                  className="w-full py-4 glass border-white/10 hover:bg-white/5 rounded-2xl text-xs font-bold uppercase tracking-widest text-white/50 hover:text-white transition-all flex items-center justify-center gap-2"
                >
                  Regenerate Analysis <Loader2 className={`w-3 h-3 ${loading ? 'animate-spin' : ''}`} />
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
};
